<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks></TargetFrameworks>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<EmbedUntrackedSources>false</EmbedUntrackedSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<AssemblyName>ZodSharp.SourceGeneration</AssemblyName>
		<NoWarn>$(NoWarn);CS1591;</NoWarn>
	</PropertyGroup>

	<ItemGroup Label="Analyzer Release Files">
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup Label="Template/ Source Files">
		<Compile Remove="Templates\Sources\**\*.cs" />
		<EmbeddedResource Include="Templates\Sources\**\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
		<PackageReference Include="Purview.SourceGeneratorFramework" PrivateAssets="all" />
	</ItemGroup>
</Project>
