using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Models;
using ZodSharp.SourceGenerators.Models.DataAttributes;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static void Execute(
		TargetSymbolDescriptor targetDescriptor,
		GenerationContext generationContext,
		SourceProductionContext context,
		bool isPrimary
	)
	{
		try
		{
			using (generationContext.Writer.Begin())
			{
				List<DiagnosticInfo> diagnostics = [];
				var source = GenerateSchemaClass(
					targetDescriptor.Symbol,
					generationContext,
					diagnostics,
					isPrimary
				);
				if (diagnostics.Count > 0)
					ReportDiagnostics(context, diagnostics, generationContext);

				var fileName = $"{targetDescriptor.Symbol.Name}Schema.g.cs";
				context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));

				// Emit module-level registration attribute for DI discovery.
				// For typeof, nested types use the CLR '+' separator (e.g. Outer+Inner).
				// Skip registration for nested types because private nested types are inaccessible at
				// assembly scope and public/internal nested types are best discovered through their
				// containing type.
				if (isPrimary && targetDescriptor.Symbol.ContainingType is null)
				{
					var registrationTypeName = targetDescriptor.Symbol.ToDisplayString();
					var registrationSource =
						@$"// <auto-generated />

[assembly: global::ZodSharp.Core.ZodSchemaGenerated(typeof(global::{registrationTypeName}))]
";
					context.AddSource(
						$"{targetDescriptor.Symbol.Name}SchemaRegistration.g.cs",
						SourceText.From(registrationSource, Encoding.UTF8)
					);
				}
			}
		}
		catch (Exception ex)
		{
			// Report diagnostic if generation fails
			var diagnostic = DiagnosticInfo.Create(
				GeneratorDiagnostics.UnhandledException,
				targetDescriptor.Declaration?.GetLocation()
					?? targetDescriptor.Symbol.Locations.FirstOrDefault(),
				targetDescriptor.Symbol.Name,
				ex.Message
			);

			ReportDiagnostics(context, diagnostic, generationContext);
		}
	}

	static List<(TargetSymbolDescriptor Descriptor, bool IsPrimary)> DiscoverAllSchemas(
		List<TargetSymbolDescriptor> primarySchemas,
		GenerationContext generationContext
	)
	{
		var result = new List<(TargetSymbolDescriptor, bool IsPrimary)>(
			primarySchemas.Select(p => (p, true))
		);
		var seen = new HashSet<INamedTypeSymbol>(
			primarySchemas.Select(p => p.Symbol),
			SymbolEqualityComparer.Default
		);
		var queue = new Queue<INamedTypeSymbol>(primarySchemas.Select(p => p.Symbol));

		while (queue.Count > 0)
		{
			var current = queue.Dequeue();
			foreach (
				var property in current
					.GetMembers()
					.OfType<IPropertySymbol>()
					.Where(static p =>
						p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic
					)
			)
			{
				var propertyType = TypeHelpers.UnwrapNullableType(property.Type);

				// Discover element types of arrays and generic collections.
				if (propertyType is IArrayTypeSymbol arrayType)
				{
					propertyType = arrayType.ElementType;
				}
				else if (propertyType is INamedTypeSymbol namedType)
				{
					var enumerableInterface = namedType.AllInterfaces.FirstOrDefault(i =>
						SymbolEqualityComparer.Default.Equals(
							i.ConstructedFrom,
							generationContext.IEnumerableOfT
						)
					);
					if (enumerableInterface is not null)
						propertyType = enumerableInterface.TypeArguments[0];
				}

				if (propertyType is not INamedTypeSymbol namedPropertyType)
					continue;

				propertyType = TypeHelpers.UnwrapNullableType(namedPropertyType);
				if (propertyType is not INamedTypeSymbol unwrappedPropertyType)
					continue;

				// Only generate schemas for source-defined types in the same compilation.
				if (!unwrappedPropertyType.Locations.Any(static l => l.IsInSource))
					continue;

				// Skip scalar types that have their own validators.
				if (IsScalarType(unwrappedPropertyType))
					continue;

				if (seen.Add(unwrappedPropertyType))
				{
					result.Add((new TargetSymbolDescriptor(unwrappedPropertyType, null), false));
					queue.Enqueue(unwrappedPropertyType);
				}
			}
		}

		return result;
	}

	static bool IsScalarType(INamedTypeSymbol type) =>
		type.SpecialType
			is SpecialType.System_Boolean
				or SpecialType.System_Char
				or SpecialType.System_SByte
				or SpecialType.System_Byte
				or SpecialType.System_Int16
				or SpecialType.System_UInt16
				or SpecialType.System_Int32
				or SpecialType.System_UInt32
				or SpecialType.System_Int64
				or SpecialType.System_UInt64
				or SpecialType.System_Single
				or SpecialType.System_Double
				or SpecialType.System_Decimal
				or SpecialType.System_String
				or SpecialType.System_DateTime
				or SpecialType.System_Object
				or SpecialType.System_IntPtr
				or SpecialType.System_UIntPtr;

	static string GenerateSchemaClass(
		INamedTypeSymbol classSymbol,
		GenerationContext generationContext,
		List<DiagnosticInfo> diagnostics,
		bool isPrimary
	)
	{
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
		var className = classSymbol.Name;
		var schemaName = $"{className}Schema";
		var codeTypeName = GetFullyQualifiedCodeTypeName(classSymbol);
		var modifier = GetSchemaClassAccessibilityKeyword(classSymbol);

		generationContext.Logger?.Info(
			$"Generating schema {schemaName} ({modifier}) for {className} in namespace {namespaceName}"
		);

		// Estimate capacity based on the number of properties
		var propertyCount = classSymbol
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Count(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

		generationContext.Logger?.Info($"Property count for {className}: {propertyCount}", 1);

		generationContext.Writer.WriteLine("// <auto-generated />");
		generationContext.Writer.WriteLine();
		generationContext.Writer.WriteLine("using System;");
		generationContext.Writer.WriteLine("using System.Collections.Generic;");
		generationContext.Writer.WriteLine("using System.Collections.Immutable;");

		generationContext.Writer.WriteLine("using ZodSharp.Core;");
		generationContext.Writer.WriteLine();

		generationContext.Writer.WriteLine($"namespace {namespaceName};");
		generationContext.Writer.WriteLine();
		generationContext.Writer.WriteLine("#nullable enable");
		generationContext.Writer.WriteLine();
		generationContext.Writer.WriteLine("/// <summary>");
		generationContext.Writer.WriteLine($"/// Auto-generated schema validator for {className}.");
		generationContext.Writer.WriteLine(
			"/// This class is generated at compile time for zero-allocation validation."
		);
		generationContext.Writer.WriteLine("/// </summary>");
		generationContext.Writer.WriteLine("{{CodeGen}}");

		var containingTypes = GetContainingTypeChain(classSymbol);
		var wrapperBlocks = new List<IDisposable>();
		foreach (var containingType in containingTypes)
		{
			var keyword = TypeHelpers.GetTypeDeclarationKeyword(containingType);
			var accessibility = TypeHelpers.GetAccessibilityKeyword(containingType);
			var header = string.IsNullOrEmpty(accessibility)
				? $"partial {keyword} {containingType.Name}"
				: $"{accessibility} partial {keyword} {containingType.Name}";
			wrapperBlocks.Add(generationContext.Writer.Block(header));
		}

		try
		{
			using (generationContext.Writer.Block($"{modifier} static partial class {schemaName}"))
			{
				generationContext.Writer.WriteLine(
					$"static readonly {TypeHelpers.ImmutableArrayMetadataName.Global()}<string> EmptyPath = {TypeHelpers.ImmutableArrayMetadataName.Global()}<string>.Empty;"
				);
				generationContext.Writer.WriteLine();
				GeneratePathFields(generationContext, classSymbol);
				GenerateStaticAttributeFields(generationContext, classSymbol, diagnostics);
				GenerateValidationHelpers(generationContext);

				GenerateValidateMethod(generationContext, classSymbol, codeTypeName, diagnostics);
				GenerateParseMethod(generationContext, codeTypeName);
				// Emit the value-first composition methods (ApplyAnd/ApplyOr/ApplyRefine).
				var compositionSb = new StringBuilder();
				GenerateCompositionMethods(compositionSb, classSymbol, codeTypeName);
				generationContext.Writer.Write(compositionSb.ToString());
			}

			// Only primary schemas get a validator adapter and custom validation lookup.
			if (isPrimary)
			{
				// Resolve the optional custom async validation method from [ZodSchema(CustomValidationMethodName = ...)].
				var zodSchemaAttribute = GetZodSchemaAttribute(classSymbol, generationContext);
				var customValidation = ResolveCustomValidationMethod(
					classSymbol,
					zodSchemaAttribute,
					generationContext
				);
				if (customValidation.Diagnostics.Length > 0)
					diagnostics.AddRange(customValidation.Diagnostics);

				GenerateValidatorAdapter(
					generationContext,
					classSymbol,
					schemaName,
					codeTypeName,
					modifier,
					customValidation
				);
			}
		}
		finally
		{
			for (var i = wrapperBlocks.Count - 1; i >= 0; i--)
				wrapperBlocks[i].Dispose();
		}

		return CodeGenHelpers.ProcessGeneratedCode(generationContext.Writer.ToString());
	}

	static ImmutableArray<INamedTypeSymbol> GetContainingTypeChain(INamedTypeSymbol typeSymbol)
	{
		var chain = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
		var current = typeSymbol.ContainingType;
		while (current is not null)
		{
			chain.Add(current);
			current = current.ContainingType;
		}

		chain.Reverse();
		return chain.ToImmutable();
	}

	static string GetSchemaClassAccessibilityKeyword(INamedTypeSymbol symbol) =>
		symbol.ContainingType is null
			? TypeHelpers.GetLimitedAccessibilityKeyword(symbol)
			: TypeHelpers.GetAccessibilityKeyword(symbol);

	static string GetFullyQualifiedCodeTypeName(INamedTypeSymbol typeSymbol)
	{
		var sb = new StringBuilder();
		sb.Append("global::");

		var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
		if (!string.IsNullOrEmpty(namespaceName))
		{
			sb.Append(namespaceName);
			sb.Append('.');
		}

		var containingTypes = new List<INamedTypeSymbol>();
		var current = typeSymbol.ContainingType;
		while (current is not null)
		{
			containingTypes.Add(current);
			current = current.ContainingType;
		}

		containingTypes.Reverse();

		foreach (var containingType in containingTypes)
		{
			sb.Append(containingType.Name);
			sb.Append('.');
		}

		sb.Append(typeSymbol.Name);
		return sb.ToString();
	}

	/// <summary>
	/// Generates a DI-friendly instance adapter class that delegates to the static {ClassName}Schema.Validate method.
	/// </summary>
	static void GenerateValidatorAdapter(
		GenerationContext generationContext,
		INamedTypeSymbol classSymbol,
		string schemaName,
		string fullTypeName,
		string modifier,
		CustomValidationMethodData customValidation
	)
	{
		generationContext.Writer.WriteLine();
		generationContext.Writer.WriteLine("/// <summary>");
		generationContext.Writer.WriteLine(
			$"/// DI-friendly validator adapter for {classSymbol.Name}, delegating to {schemaName}."
		);
		generationContext.Writer.WriteLine("/// </summary>");
		generationContext.Writer.WriteLine("{{CodeGen}}");
		using (
			generationContext.Writer.Block(
				$"{modifier} sealed partial class {schemaName}Validator : global::ZodSharp.Core.IZodSchemaValidator<{fullTypeName}>"
			)
		)
		{
			generationContext.Writer.WriteLine(
				$"public global::ZodSharp.Core.ValidationResult<{fullTypeName}> Validate({fullTypeName} value)"
			);
			using (generationContext.Writer.Block())
			{
				generationContext.Writer.WriteLine($"return {schemaName}.Validate(value);");
			}

			generationContext.Writer.WriteLine();
			GenerateValidateAsyncMethod(
				generationContext,
				schemaName,
				fullTypeName,
				customValidation
			);
		}
	}

	/// <summary>
	/// Generates the ValidateAsync method on the adapter. When a valid custom async
	/// validation method exists, it awaits the custom method and merges results.
	/// Otherwise, it returns the synchronous result in a completed ValueTask
	/// without an async state machine.
	/// </summary>
	static void GenerateValidateAsyncMethod(
		GenerationContext generationContext,
		string schemaName,
		string fullTypeName,
		CustomValidationMethodData customValidation
	)
	{
		var validationResultGlobal = TypeHelpers.ValidationResult.Global();
		var ctParam = "global::System.Threading.CancellationToken cancellationToken = default";

		if (!customValidation.HasCustomValidation)
		{
			// No custom method — synchronous fallback, no async state machine.
			generationContext.Writer.WriteLine(
				$"public global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{fullTypeName}>> ValidateAsync({fullTypeName} value, {ctParam})"
			);
			using (generationContext.Writer.Block())
			{
				generationContext.Writer.WriteLine(
					$"return global::System.Threading.Tasks.ValueTask.FromResult({schemaName}.Validate(value));"
				);
			}

			return;
		}

		// Custom async validation path — async state machine is required here.
		generationContext.Writer.WriteLine(
			$"public async global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{fullTypeName}>> ValidateAsync({fullTypeName} value, {ctParam})"
		);
		using (generationContext.Writer.Block())
		{
			generationContext.Writer.WriteLine($"var syncResult = {schemaName}.Validate(value);");

			var escapedMethodName = customValidation.MethodName;
			var validationMethodPrefix =
				customValidation.InvocationKind
				== CustomValidationInvocationKind.DefinedOnSchemaValidator
					? ""
					: $"{fullTypeName}.";

			generationContext.Writer.WriteLine(
				$"var customResult = await {validationMethodPrefix}{escapedMethodName}(value, cancellationToken).ConfigureAwait(false);"
			);

			generationContext.Writer.WriteLine();
			generationContext.Writer.WriteLine(
				$"return {validationResultGlobal}<{fullTypeName}>.Merge(syncResult, customResult);"
			);
		}
	}

	static void GenerateValidateMethod(
		GenerationContext generationContext,
		INamedTypeSymbol classSymbol,
		string fullTypeName,
		List<DiagnosticInfo> diagnostics
	)
	{
		var writer = generationContext.Writer;
		writer.WriteLine("/// <summary>");
		writer.WriteLine("/// Validates an instance of the target type.");
		writer.WriteLine("/// </summary>");
		writer.WriteLine(
			$"public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Validate({fullTypeName} value)"
		);

		using (writer.Block())
		{
			if (TypeHelpers.CanBeNull(classSymbol))
			{
				using (writer.Block("if (value == null)"))
				{
					using (
						writer.Block(
							$"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure",
							seperator: "(",
							closingSeperator: ");"
						)
					)
					{
						using (
							writer.Block(
								$"{TypeHelpers.ValidationError.Global()}.Create",
								seperator: "("
							)
						)
						{
							writer.WriteIndent().Quote("invalid_type").Write(",").NewLine();
							writer.WriteIndent().Quote("Value cannot be null").Write(",").NewLine();
							writer.WriteIndent().Write("EmptyPath").NewLine();
						}
					}
				}

				writer.NewLine();
			}

			writer.WriteLine(
				$"{typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors = null;"
			);

			var properties = classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
				.ToList();

			foreach (var property in properties)
				GeneratePropertyValidation(generationContext, property, diagnostics);

			using (writer.Block("if (errors is not null)"))
			{
				writer.WriteLine(
					$"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(errors);"
				);
			}

			writer
				.WriteLine()
				.WriteLine(
					$"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);"
				);
		}
	}

	static void GeneratePropertyValidation(
		GenerationContext generationContext,
		IPropertySymbol property,
		List<DiagnosticInfo> diagnostics
	)
	{
		var propertyName = property.Name;
#pragma warning disable format
		var propertyType = property.Type
			is INamedTypeSymbol
			{
				OriginalDefinition.SpecialType: SpecialType.System_Nullable_T
			} nullableType
			? nullableType.TypeArguments[0]
			: property.Type;
#pragma warning restore format
		var canBeNull = TypeHelpers.CanBeNull(property.Type);

		var attributes = property.GetAttributes();
		var requiredAttrib = RequiredAttributeData.FromAttributeData(generationContext, attributes);

		IDisposable? block = null;
		if (canBeNull && requiredAttrib.Exists)
		{
			var isStringAndAllowEmptyStrings =
				propertyType.SpecialType == SpecialType.System_String
				&& requiredAttrib.AllowEmptyStrings;
			var localErrorMessage = isStringAndAllowEmptyStrings
				? "Field '{0}' is required and cannot be null or empty"
				: "Required field '{0}' is null";

			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				requiredAttrib.ErrorMessage ?? localErrorMessage,
				propertyName
			);

			var comparision = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			generationContext.Writer.WriteRule(
				propertyName,
				comparision,
				"missing_field",
				errorMessage
			);

			block = generationContext.Writer.Block("else");
			GenerateValueSetValidations(
				generationContext,
				property,
				property.Type,
				propertyName,
				attributes,
				diagnostics
			);
		}
		else
		{
			GenerateValueSetValidations(
				generationContext,
				property,
				property.Type,
				propertyName,
				attributes,
				diagnostics
			);

			if (canBeNull)
				block = generationContext.Writer.Block($"if (value.{propertyName} != null)");
		}

		GenerateTypeSpecificValidations(
			generationContext,
			property,
			propertyType,
			attributes,
			propertyName,
			canBeNull,
			diagnostics
		);

		block?.Dispose();

		generationContext.Writer.WriteLine();
	}

	static void GenerateTypeSpecificValidations(
		GenerationContext generationContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		bool canBeNull,
		List<DiagnosticInfo> diagnostics
	)
	{
		var lengthAttributeData = FindAttribute(attributes, generationContext.LengthAttribute);
		var supportsLengthAttribute =
			propertyType.SpecialType == SpecialType.System_String
			|| propertyType is IArrayTypeSymbol
			|| TypeHelpers.ImplementsInterface(propertyType, generationContext.IEnumerable)
			|| TypeHelpers.ImplementsInterface(propertyType, generationContext.IEnumerableOfT);

		if (lengthAttributeData is not null && !supportsLengthAttribute)
			AddUnsupportedLengthTargetDiagnostic(
				diagnostics,
				lengthAttributeData,
				propertyName,
				propertyType
			);

		var rangeAttributeData = FindAttribute(attributes, generationContext.RangeAttribute);
		if (
			rangeAttributeData is not null
			&& !TryBuildRangeBoundaryExpressions(
				propertyType,
				RangeAttributeData.FromAttributeData(generationContext, rangeAttributeData),
				out _,
				out _
			)
		)
		{
			AddUnsupportedDataAnnotationsDiagnostic(
				diagnostics,
				rangeAttributeData,
				string.Format(
					CultureInfo.InvariantCulture,
					"RangeAttribute on '{0}' cannot be generated safely for '{1}'.",
					propertyName,
					propertyType.ToDisplayString()
				)
			);
		}

		if (propertyType.SpecialType == SpecialType.System_String)
		{
			GenerateStringValidations(
				generationContext,
				property,
				propertyName,
				attributes,
				diagnostics
			);
		}
		else if (TypeHelpers.IsNumericType(propertyType))
		{
			GenerateNumericValidations(
				generationContext,
				property,
				propertyType,
				propertyName,
				attributes,
				diagnostics
			);
		}
		else if (
			propertyType is IArrayTypeSymbol
			|| TypeHelpers.ImplementsInterface(propertyType, generationContext.IEnumerable)
			|| TypeHelpers.ImplementsInterface(propertyType, generationContext.IEnumerableOfT)
		)
		{
			GenerateCollectionValidations(
				generationContext,
				property,
				propertyType,
				propertyName,
				attributes,
				diagnostics
			);

			var elementType = GetCollectionElementType(propertyType, generationContext);
			if (
				elementType is INamedTypeSymbol namedElementType
				&& (
					TypeHelpers.HasZodSchemaAttribute(
						namedElementType,
						generationContext.ZodSchemaAttribute
					) || IsSourceDefinedComplexType(namedElementType)
				)
			)
			{
				GenerateCollectionElementValidation(
					generationContext,
					property,
					elementType,
					propertyName
				);
			}
		}
		else if (
			propertyType is INamedTypeSymbol namedPropertyType
			&& (
				TypeHelpers.HasZodSchemaAttribute(
					namedPropertyType,
					generationContext.ZodSchemaAttribute
				) || IsSourceDefinedComplexType(namedPropertyType)
			)
		)
		{
			GenerateComplexTypeValidation(
				generationContext,
				property,
				propertyType,
				propertyName,
				canBeNull
			);
		}
	}

	static bool IsSourceDefinedComplexType(INamedTypeSymbol type) =>
		type.Locations.Any(static l => l.IsInSource) && IsComplexType(type);

	static bool IsComplexType(INamedTypeSymbol type) =>
		!IsScalarType(type) && type.TypeKind is not TypeKind.Enum;

	static ITypeSymbol? GetCollectionElementType(
		ITypeSymbol propertyType,
		GenerationContext generationContext
	)
	{
		if (propertyType is IArrayTypeSymbol arrayType)
			return arrayType.ElementType;

		if (propertyType is not INamedTypeSymbol namedType)
			return null;

		foreach (var iface in namedType.AllInterfaces)
		{
			if (
				SymbolEqualityComparer.Default.Equals(
					iface.ConstructedFrom,
					generationContext.IEnumerableOfT
				)
			)
				return iface.TypeArguments[0];
		}

		if (
			namedType.IsGenericType
			&& SymbolEqualityComparer.Default.Equals(
				namedType.ConstructedFrom,
				generationContext.IEnumerableOfT
			)
		)
		{
			return namedType.TypeArguments[0];
		}

		// If the property type implements IEnumerable but not IEnumerable<T>, we cannot determine the element type.
		return null;
	}

	static void GenerateCollectionElementValidation(
		GenerationContext generationContext,
		IPropertySymbol property,
		ITypeSymbol elementType,
		string propertyName
	)
	{
		generationContext.Logger?.Debug(
			$"Generating collection element validation for property '{property.Name}' of type '{elementType.ToDisplayString()}'",
			1
		);

		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)elementType);
		var collectionValueName = GetLocalIdentifier(propertyName, "Collection");
		var itemValueName = GetLocalIdentifier(propertyName, "Item");
		var itemResultName = GetLocalIdentifier(propertyName, "ItemResult");
		var indexName = GetLocalIdentifier(propertyName, "Index");
		var canItemBeNull = TypeHelpers.CanBeNull(elementType);

		generationContext.Writer.WriteLine($"var {collectionValueName} = value.{propertyName};");
		using (generationContext.Writer.Block($"if ({collectionValueName} is not null)"))
		{
			generationContext.Writer.WriteLine($"var {indexName} = 0;");
			generationContext.Writer.WriteLine(
				$"foreach (var {itemValueName} in {collectionValueName})"
			);
			using (generationContext.Writer.Block())
			{
				if (canItemBeNull)
				{
					using (generationContext.Writer.Block($"if ({itemValueName} is not null)"))
					{
						generationContext.Writer.WriteLine(
							$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
						);
						using (generationContext.Writer.Block($"if (!{itemResultName}.IsSuccess)"))
						{
							generationContext.Writer.WriteLine(
								$"AddNestedErrors(ref errors, {itemResultName}, {Quote(propertyName)}, {indexName});"
							);
						}
					}
				}
				else
				{
					generationContext.Writer.WriteLine(
						$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
					);
					using (generationContext.Writer.Block($"if (!{itemResultName}.IsSuccess)"))
					{
						generationContext.Writer.WriteLine(
							$"AddNestedErrors(ref errors, {itemResultName}, {Quote(propertyName)}, {indexName});"
						);
					}
				}

				generationContext.Writer.WriteLine($"{indexName}++;");
			}
		}

		generationContext.Writer.WriteLine();
	}

	static void GenerateComplexTypeValidation(
		GenerationContext generationContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		string propertyName,
		bool canBeNull
	)
	{
		generationContext.Logger?.Debug(
			$"Generating complex type validation for property '{property.Name}' of type '{propertyType.ToDisplayString()}'",
			1
		);
		var propertyValueName = GetLocalIdentifier(propertyName, "Value");
		var nestedResultName = GetLocalIdentifier(propertyName, "Result");
		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)propertyType);

		generationContext.Writer.WriteLine($"var {propertyValueName} = value.{propertyName};");
		if (canBeNull)
		{
			using (generationContext.Writer.Block($"if ({propertyValueName} is not null)"))
			{
				generationContext.Writer.WriteLine(
					$"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});"
				);
				using (generationContext.Writer.Block($"if (!{nestedResultName}.IsSuccess)"))
				{
					generationContext.Writer.WriteLine(
						$"AddNestedErrors(ref errors, {nestedResultName}, {Quote(propertyName)});"
					);
				}
			}
		}
		else
		{
			generationContext.Writer.WriteLine(
				$"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});"
			);
			using (generationContext.Writer.Block($"if (!{nestedResultName}.IsSuccess)"))
			{
				generationContext.Writer.WriteLine(
					$"AddNestedErrors(ref errors, {nestedResultName}, {Quote(propertyName)});"
				);
			}
		}
	}

	static void GeneratePathFields(
		GenerationContext generationContext,
		INamedTypeSymbol classSymbol
	)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			generationContext.Writer.WriteLine(
				$"static readonly {TypeHelpers.ImmutableArrayMetadataName.Global()}<string> {GetPathFieldName(property.Name)} = {TypeHelpers.ImmutableArrayMetadataName.Global()}.Create({Quote(property.Name)});"
			);
		}

		generationContext.Writer.WriteLine();
	}

	static void GenerateStaticAttributeFields(
		GenerationContext generationContext,
		INamedTypeSymbol classSymbol,
		List<DiagnosticInfo> diagnostics
	)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			var attributes = property.GetAttributes();
			var propertyType = TypeHelpers.UnwrapNullableType(property.Type);

			var regexAttribute = RegularExpressionAttributeData.FromAttributeData(
				generationContext,
				attributes
			);
			if (regexAttribute.Exists)
			{
				if (
					propertyType.SpecialType != SpecialType.System_String
					|| string.IsNullOrEmpty(regexAttribute.Pattern)
				)
				{
					AddUnsupportedDataAnnotationsDiagnostic(
						diagnostics,
						FindAttribute(attributes, generationContext.RegularExpressionAttribute),
						string.Format(
							CultureInfo.InvariantCulture,
							"RegularExpressionAttribute can only be applied to string properties, but '{0}' is '{1}'.",
							property.Name,
							propertyType.ToDisplayString()
						)
					);
				}
				else
				{
					generationContext.Writer.WriteLine(
						$"static readonly global::System.Text.RegularExpressions.Regex {GetRegexFieldName(property.Name)} = new({Quote(regexAttribute.Pattern!)}, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);"
					);
				}
			}

			var rangeAttribute = RangeAttributeData.FromAttributeData(
				generationContext,
				attributes
			);
			if (
				rangeAttribute.Exists
				&& TryBuildRangeBoundaryExpressions(
					propertyType,
					rangeAttribute,
					out var minimumExpression,
					out var maximumExpression
				)
			)
			{
				var fqTypeName = GetFullyQualifiedTypeName(propertyType);
				generationContext.Writer.WriteLine(
					$"static readonly {fqTypeName} {GetRangeMinimumFieldName(property.Name)} = {minimumExpression};"
				);
				generationContext.Writer.WriteLine(
					$"static readonly {fqTypeName} {GetRangeMaximumFieldName(property.Name)} = {maximumExpression};"
				);
			}
		}

		generationContext.Writer.WriteLine();
	}

	static void GenerateValidationHelpers(GenerationContext generationContext)
	{
		var writer = generationContext.Writer;
		writer.WriteLine(
			$"static void AddError(ref {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors, {TypeHelpers.ValidationError.Global()} error)"
		);
		using (writer.Block())
		{
			writer.WriteLine(
				$"(errors ??= new {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>()).Add(error);"
			);
		}

		writer.WriteLine();
		writer.WriteLine(
			$"static void AddNestedErrors<T>(ref {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors, {TypeHelpers.ValidationResult.Global()}<T> nestedResult, string prefix)"
		);
		using (writer.Block())
		{
			writer.WriteLine("foreach (var error in nestedResult.Errors)");
			using (writer.Block())
			{
				writer.WriteLine(
					$"AddError(ref errors, {TypeHelpers.ValidationError.Global()}.Create("
				);
				writer.Indent();
				writer.WriteLine("error.Code,");
				writer.WriteLine("error.Message,");
				writer.WriteLine(
					$"{TypeHelpers.ImmutableArrayMetadataName.Global()}.Create(prefix).AddRange(error.Path),"
				);
				writer.WriteLine("error.Parameters,");
				writer.WriteLine("error.Origin,");
				writer.WriteLine("error.Minimum,");
				writer.WriteLine("error.Maximum,");
				writer.WriteLine("error.Inclusive");
				writer.Unindent();
				writer.WriteLine("));");
			}
		}

		writer.WriteLine();
		writer.WriteLine(
			$"static void AddNestedErrors<T>(ref {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors, {TypeHelpers.ValidationResult.Global()}<T> nestedResult, string prefix, int index)"
		);
		using (writer.Block())
		{
			writer.WriteLine("foreach (var error in nestedResult.Errors)");
			using (writer.Block())
			{
				writer.WriteLine(
					$"AddError(ref errors, {TypeHelpers.ValidationError.Global()}.Create("
				);
				writer.Indent();
				writer.WriteLine("error.Code,");
				writer.WriteLine("error.Message,");
				writer.WriteLine(
					$"{TypeHelpers.ImmutableArrayMetadataName.Global()}.Create(prefix, index.ToString()).AddRange(error.Path),"
				);
				writer.WriteLine("error.Parameters,");
				writer.WriteLine("error.Origin,");
				writer.WriteLine("error.Minimum,");
				writer.WriteLine("error.Maximum,");
				writer.WriteLine("error.Inclusive");
				writer.Unindent();
				writer.WriteLine("));");
			}
		}

		writer.WriteLine();
		writer.WriteLine(
			"static string FormatCount(int count, string singularNoun, string pluralNoun)"
		);
		using (writer.Block())
		{
			writer.WriteLine(
				"return count == 1 ? $\"1 {singularNoun}\" : $\"{count} {pluralNoun}\";"
			);
		}

		writer.WriteLine();
	}

	static string GetPathFieldName(string propertyName) => $"Path_{propertyName}";

	static string GetLocalIdentifier(string propertyName, string suffix) =>
		string.IsNullOrEmpty(propertyName)
			? suffix
			: char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + suffix;

	static string Quote(string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

	static void GenerateParseMethod(GenerationContext generationContext, string fullTypeName)
	{
		generationContext.Writer.WriteLine("/// <summary>");
		generationContext.Writer.WriteLine(
			"/// Validates and returns the value, throwing an exception if validation fails."
		);
		generationContext.Writer.WriteLine("/// </summary>");
		generationContext.Writer.WriteLine(
			$"public static {fullTypeName} Parse({fullTypeName} value)"
		);
		using (generationContext.Writer.Block())
		{
			generationContext.Writer.WriteLine("return Validate(value).GetValueOrThrow();");
		}
	}

	static void GenerateCompositionMethods(
		StringBuilder sb,
		INamedTypeSymbol classSymbol,
		string fullTypeName
	)
	{
		sb.AppendLine();
		sb.AppendLine("    /// <summary>");
		sb.AppendLine(
			"    /// Validates the value and then requires an additional predicate to pass (value-first .and())."
		);
		sb.AppendLine("    /// Equivalent to Zod's .and() semantics applied to a value.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> ApplyAnd({fullTypeName} value, global::System.Func<{fullTypeName}, bool> additionalValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!additionalValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine(
			$"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure("
		);
		sb.AppendLine($"                {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                    \"validation_failed\",");
		sb.AppendLine(
			$"                    message ?? \"Additional validation failed for {classSymbol.Name}\","
		);
		sb.AppendLine("                    EmptyPath");
		sb.AppendLine("                )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine(
			"    /// Validates the value and accepts it if either the schema or an alternative predicate passes (value-first .or())."
		);
		sb.AppendLine("    /// Equivalent to Zod's .or() semantics applied to a value.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> ApplyOr({fullTypeName} value, global::System.Func<{fullTypeName}, bool> alternativeValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (alternativeValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine(
			$"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);"
		);
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine(
			$"        return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure("
		);
		sb.AppendLine($"            {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine(
			$"                message ?? \"Neither validation passed for {classSymbol.Name}\","
		);
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("        );");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine(
			"    /// Validates the value and then runs a custom refinement predicate (value-first .refine())."
		);
		sb.AppendLine("    /// Equivalent to Zod's .refine() semantics applied to a value.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> ApplyRefine({fullTypeName} value, global::System.Func<{fullTypeName}, bool> refinement, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!refinement(value))");
		sb.AppendLine("        {");
		sb.AppendLine(
			$"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure("
		);
		sb.AppendLine($"            {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine(
			$"                message ?? \"Refinement validation failed for {classSymbol.Name}\","
		);
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
	}
}
