using System.Collections.Immutable;
using System.Globalization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Models;
using ZodSharp.SourceGenerators.Models.DataAttributes;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static IEnumerable<(string? HintName, SourceText Source)> BuildSchema(
		SchemaGenerationOutputContext outputContext,
		SourceProductionContext context,
		bool isPrimary
	)
	{
		outputContext.Info($"Building schema for {outputContext.ZodSchema.TargetType.MetadataFullName}");

		List<DiagnosticInfo> diagnostics = [];
		context.CancellationToken.ThrowIfCancellationRequested();
		var writer = GenerateSchemaClass(outputContext, diagnostics, isPrimary, context.CancellationToken);
		if (diagnostics.Count > 0)
			ReportDiagnostics(context, diagnostics, outputContext);

		context.CancellationToken.ThrowIfCancellationRequested();

		yield return (outputContext.ZodSchema.TargetType.Name + "Schema.g.cs", writer);

		// Emit module-level registration attribute for DI discovery.
		// For typeof, nested types use the CLR '+' separator (e.g. Outer+Inner).
		// Skip registration for nested types because private nested types are inaccessible at
		// assembly scope and public/internal
		//NOT TRUE ANYMORE
		// nested types are best discovered through their
		// containing type.
		if (isPrimary) // && schemaSymbol.ContainingType is null)
		{
			// Create a new writer for the assembly-level attribute to avoid polluting the schema class file.
			writer = outputContext.Context.CreateCodeWriter();

			writer.WriteAutoGeneratedHeader();
			writer
				.Write("[assembly: global::")
				.Write(TypeLibrary.ZodSchemaGeneratedAttribute.MetadataFullName)
				.Write("(typeof(")
				.Write(outputContext.ZodSchema.TargetType)
				.WriteLine("))]");

			context.CancellationToken.ThrowIfCancellationRequested();

			yield return (outputContext.ZodSchema.TargetType.Name + "SchemaRegistration.g.cs", writer);
		}
	}

	internal static bool IsScalarType(INamedTypeSymbol type) =>
		type.SpecialType
			is SpecialType.System_Boolean
				or SpecialType.System_Char
				or SpecialType.System_SByte
				or SpecialType.System_Byte
				or SpecialType.System_Int16
				or SpecialType.System_UInt16
				or SpecialType.System_Int32
				or SpecialType.System_UInt32
				or SpecialType.System_Int64
				or SpecialType.System_UInt64
				or SpecialType.System_Single
				or SpecialType.System_Double
				or SpecialType.System_Decimal
				or SpecialType.System_String
				or SpecialType.System_DateTime
				or SpecialType.System_Object
				or SpecialType.System_IntPtr
				or SpecialType.System_UIntPtr;

	static CodeWriter GenerateSchemaClass(
		SchemaGenerationOutputContext outputContext,
		List<DiagnosticInfo> diagnostics,
		bool isPrimary,
		CancellationToken cancellationToken
	)
	{
		outputContext.Info(
			$"Generating schema {outputContext.ZodSchema.SchemaType.Name} ({outputContext.ZodSchema.TargetAccessibility}) for {outputContext.ZodSchema.TargetType.Name} in namespace {outputContext.ZodSchema.TargetType.Namespace ?? "<<global namespace>>"}"
		);

		outputContext.Info(
			$"Property count for {outputContext.ZodSchema.TargetType.Name}: {outputContext.ZodSchema.Properties.Count}",
			1
		);

		var writer = outputContext.Writer;

		writer.WriteAutoGeneratedHeader();
		writer
			.WriteUsing("System")
			.WriteUsing("System.Collections.Generic")
			.WriteUsing("System.Collections.Immutable")
			.WriteUsing(TypeLibrary.ZodSharpCoreNamespace)
			.NewLine();

		using (writer.WriteBlockNamespaceScope(outputContext.ZodSchema.TargetType))
		{
			writer.XmlSummary(
				$"Auto-generated schema validator for  {CodeWriter.XmlSee(outputContext.ZodSchema.TargetType.Name)}.",
				"This class is generated at compile time for zero-allocation validation."
			);

			List<IDisposable> wrapperBlocks = [];
			foreach (var containingTypeDeclaration in outputContext.ZodSchema.ContainingTypes)
				wrapperBlocks.Add(writer.WriteTypeScope(containingTypeDeclaration));

			using (
				writer.WriteClassScope(
					new(outputContext.ZodSchema.SchemaType, outputContext.ZodSchema.TargetAccessibility)
					{
						IsPartial = true,
						IsStatic = true,
					}
				)
			)
			{
				writer.WriteField(
					new(
						"EmptyPath",
						TypeLibrary.Collections.ImmutableArray.MakeGeneric(PurviewTypeLibrary.System.String),
						TypeDeclarationAccessibility.Private
					)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = "[]",
					}
				);

				GeneratePathFields(outputContext, cancellationToken);
				GenerateStaticAttributeFields(outputContext, cancellationToken);
				GenerateValidationHelpers(outputContext, cancellationToken);

				GenerateValidateMethod(outputContext, cancellationToken);
				GenerateParseMethod(outputContext, cancellationToken);

				// Emit the value-first composition methods (ApplyAnd/ApplyOr/ApplyRefine).
				GenerateCompositionMethods(outputContext, cancellationToken);
			}

			// Only primary schemas get a validator adapter and custom validation lookup.
			if (isPrimary)
			{
				if (outputContext.ZodSchema.CustomValidationMethod.ShouldProcess)
					GenerateValidatorAdapter(outputContext, cancellationToken);
			}

			foreach (var block in wrapperBlocks)
				block.Dispose();
		}

		return writer;
	}

	/// <summary>
	/// Generates a DI-friendly instance adapter class that delegates to the static {ClassName}Schema.Validate method.
	/// </summary>
	static void GenerateValidatorAdapter(
		SchemaGenerationOutputContext outputContext,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		outputContext
			.Writer.XmlSummary(
				$"DI-friendly validator adapter for {outputContext.ZodSchema.TargetType.Name}, delegating to {outputContext.ZodSchema.SchemaType.Name}."
			)
			.WriteClass(
				new(outputContext.ZodSchema.SchemaType, outputContext.ZodSchema.TargetAccessibility)
				{
					BaseType = TypeLibrary.IZodSchemaValidator.MakeGeneric(outputContext.ZodSchema.TargetType),
				},
				writer =>
				{
					outputContext.Writer.WriteMethod(
						new(
							"Validate",
							TypeLibrary.ValidationResult.MakeGeneric(outputContext.ZodSchema.TargetType),
							TypeDeclarationAccessibility.Public
						),
						methodBody =>
							methodBody.WriteReturn($"{outputContext.ZodSchema.SchemaType.Name}.Validate(value)")
					);

					GenerateValidateAsyncMethod(outputContext, cancellationToken);
				}
			);
	}

	/// <summary>
	/// Generates the ValidateAsync method on the adapter. When a valid custom async
	/// validation method exists, it awaits the custom method and merges results.
	/// Otherwise, it returns the synchronous result in a completed ValueTask
	/// without an async state machine.
	/// </summary>
	static void GenerateValidateAsyncMethod(
		SchemaGenerationOutputContext outputContext,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		outputContext.Info(
			$"Generating ValidateAsync method for {outputContext.ZodSchema.SchemaType.Name}Validator with custom validation: {outputContext.ZodSchema.CustomValidationMethod.Value.MethodName}",
			1
		);

		var validationResultGlobal = TypeLibrary.ValidationResult;
		var ctParam = "global::System.Threading.CancellationToken cancellationToken = default";

		if (!outputContext.ZodSchema.CustomValidationMethod.Value.HasCustomValidation)
		{
			// No custom method — synchronous fallback, no async state machine.
			outputContext.Writer.WriteLine(
				$"public global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{outputContext.ZodSchema.TargetType}>> ValidateAsync({outputContext.ZodSchema.TargetType} value, {ctParam})"
			);
			using (outputContext.Writer.OpenBlockScope())
			{
				outputContext.Writer.WriteLine(
					$"return global::System.Threading.Tasks.ValueTask.FromResult({outputContext.ZodSchema.SchemaType.Name}.Validate(value));"
				);
			}

			return;
		}

		// Custom async validation path — async state machine is required here.
		outputContext.Writer.WriteLine(
			$"public async global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{outputContext.ZodSchema.TargetType}>> ValidateAsync({outputContext.ZodSchema.TargetType} value, {ctParam})"
		);
		using (outputContext.Writer.OpenBlockScope())
		{
			outputContext.Writer.WriteLine(
				$"var syncResult = {outputContext.ZodSchema.SchemaType.Name}.Validate(value);"
			);

			var escapedMethodName = outputContext.ZodSchema.CustomValidationMethod.Value.MethodName;
			var validationMethodPrefix =
				outputContext.ZodSchema.CustomValidationMethod.Value.InvocationKind
				== CustomValidationInvocationKind.DefinedOnSchemaValidator
					? ""
					: $"{outputContext.ZodSchema.TargetType}.";

			outputContext.Writer.WriteLine(
				$"var customResult = await {validationMethodPrefix}{escapedMethodName}(value, cancellationToken).ConfigureAwait(false);"
			);

			outputContext.Writer.WriteLine();
			outputContext.Writer.WriteLine(
				$"return {validationResultGlobal.MakeGeneric(outputContext.ZodSchema.TargetType.Name)}.Merge(syncResult, customResult);"
			);
		}
	}

	static void GenerateValidateMethod(SchemaGenerationOutputContext outputContext, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();

		outputContext
			.Writer.XmlSummary("Validates an instance of the target type.")
			.WriteLine(
				$"public static {TypeLibrary.ValidationResult.MakeGeneric(outputContext.ZodSchema.TargetType)} Validate({outputContext.ZodSchema.TargetType} value)"
			);

		using (outputContext.Writer.OpenBlockScope())
		{
			if (outputContext.ZodSchema.TargetCanBeNull)
			{
				outputContext.Writer.WriteBlock(
					"if (value == null)",
					ifBody =>
						ifBody.WriteDelimitedBlock(
							$"return {TypeLibrary.ValidationResult.MakeGeneric(outputContext.ZodSchema.TargetType)}.Failure",
							"(",
							");",
							failureArguments =>
								failureArguments.WriteDelimitedBlock(
									$"{TypeLibrary.ValidationError}.Create",
									"(",
									")",
									errorArguments =>
									{
										errorArguments.Quote("invalid_type").WriteLine(",");
										errorArguments.Quote("Value cannot be null").WriteLine(",");
										errorArguments.WriteLine("EmptyPath");
									}
								)
						)
				);
			}

			outputContext
				.Writer.NewLine()
				.WriteLine($"{TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}? errors = null;");

			foreach (var property in outputContext.ZodSchema.Properties)
			{
				if (property.ShouldProcess)
					GeneratePropertyValidation(outputContext, property.Value, cancellationToken);
			}

			using (outputContext.Writer.OpenBlockScope("if (errors is not null)"))
			{
				outputContext.Writer.WriteLine(
					$"return {TypeLibrary.ValidationResult}<{outputContext.ZodSchema.TargetType}>.Failure(errors);"
				);
			}

			outputContext
				.Writer.WriteLine()
				.WriteLine(
					$"return {TypeLibrary.ValidationResult}<{outputContext.ZodSchema.TargetType}>.Success(value);"
				);
		}

		outputContext.Writer.NewLine();
	}

	static void GeneratePropertyValidation(
		SchemaGenerationOutputContext outputContext,
		ZodPropertyDescriptor property,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var propertyName = property.Name;
		var propertyType = property.PropertyType;
		CodeWriter.BlockScope? block = null;
		if (
			property.CanBeNull
			&& property.ValidationAttributes.Required.ShouldProcess
			&& property.ValidationAttributes.Required.Value.Exists
		)
		{
			var isStringAndAllowEmptyStrings =
				propertyType.SpecialType == SpecialType.System_String
				&& property.ValidationAttributes.Required.Value.AllowEmptyStrings;
			var localErrorMessage = isStringAndAllowEmptyStrings
				? "Field '{0}' is required and cannot be null or empty"
				: "Required field '{0}' is null";

			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				property.ValidationAttributes.Required.Value.ValidationAttribute.ErrorMessage ?? localErrorMessage,
				propertyName
			);

			var comparision = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			outputContext.Writer.WriteRule(propertyName, comparision, "missing_field", errorMessage);

			block = outputContext.Writer.OpenBlockScope("else");
			GenerateValueSetValidations(outputContext, property);
		}
		else
		{
			GenerateValueSetValidations(outputContext, property);

			if (property.CanBeNull)
				block = outputContext.Writer.OpenBlockScope($"if (value.{propertyName} != null)");
		}

		GenerateTypeSpecificValidations(
			outputContext,
			property,
			propertyType,
			attributes,
			propertyName,
			canBeNull,
			diagnostics
		);

		block?.Dispose();

		GenerateCompareValidation(
			outputContext,
			property,
			property.ContainingType,
			attributes,
			propertyName,
			diagnostics
		);

		outputContext.Writer.WriteLine();
	}

	static void GenerateTypeSpecificValidations(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		bool canBeNull,
		List<DiagnosticInfo> diagnostics
	)
	{
		LengthAttributeData.FromAttributeData(attributes, out var lengthAttributeData);
		var supportsLengthAttribute =
			propertyType.SpecialType == SpecialType.System_String
			|| propertyType is IArrayTypeSymbol
			|| TypeHelpers.IsOrImplements(propertyType, TypeLibrary.Collections.IEnumerable)
			|| TypeHelpers.IsOrImplements(propertyType, TypeLibrary.Collections.IEnumerableT);

		if (lengthAttributeData is not null && !supportsLengthAttribute)
		{
			AddUnsupportedLengthTargetDiagnostic(diagnostics, lengthAttributeData, propertyName, propertyType);
		}

		var rangeAttribute = RangeAttributeData.FromAttributeData(attributes, out var rangeAttributeData);
		if (
			rangeAttributeData is not null
			&& !TryBuildRangeBoundaryExpressions(propertyType, rangeAttribute, out _, out _)
		)
		{
			AddUnsupportedDataAnnotationsDiagnostic(
				diagnostics,
				rangeAttributeData,
				string.Format(
					CultureInfo.InvariantCulture,
					"RangeAttribute on '{0}' cannot be generated safely for '{1}'.",
					propertyName,
					propertyType.ToDisplayString()
				)
			);
		}

		if (propertyType.SpecialType != SpecialType.System_String)
		{
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.UrlAttribute,
				nameof(TypeLibrary.DataAnnotations.UrlAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.PhoneAttribute,
				nameof(TypeLibrary.DataAnnotations.PhoneAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.CreditCardAttribute,
				nameof(TypeLibrary.DataAnnotations.CreditCardAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.Base64StringAttribute,
				nameof(TypeLibrary.DataAnnotations.Base64StringAttribute)
			);
		}

		if (propertyType.SpecialType == SpecialType.System_String)
		{
			GenerateStringValidations(outputContext, property, propertyName, attributes, diagnostics);
		}
		else if (TypeHelpers.IsNumericType(propertyType))
		{
			GenerateNumericValidations(outputContext, property, propertyType, propertyName, attributes, diagnostics);
		}
		else if (
			propertyType is IArrayTypeSymbol
			|| TypeHelpers.Implements(propertyType, TypeLibrary.Collections.IEnumerable)
			|| TypeHelpers.Implements(propertyType, TypeLibrary.Collections.IEnumerableT)
		)
		{
			GenerateCollectionValidations(outputContext, property, propertyType, propertyName, attributes, diagnostics);

			var elementType = GetCollectionElementType(propertyType);
			if (
				elementType is INamedTypeSymbol namedElementType
				&& (TypeHelpers.HasZodSchemaAttribute(namedElementType) || IsSourceDefinedComplexType(namedElementType))
			)
			{
				GenerateCollectionElementValidation(outputContext, property, elementType, propertyName);
			}
		}
		else if (
			propertyType is INamedTypeSymbol namedPropertyType
			&& (TypeHelpers.HasZodSchemaAttribute(namedPropertyType) || IsSourceDefinedComplexType(namedPropertyType))
		)
		{
			GenerateComplexTypeValidation(outputContext, property, propertyType, propertyName, canBeNull);
		}
	}

	static void CheckUnsupportedStringOnlyAttribute(
		List<DiagnosticInfo> diagnostics,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		ITypeSymbol propertyType,
		TypeIdentity attributeType,
		string attributeName
	)
	{
		var attributeData = attributes.FirstOrDefault(a => attributeType.Equals(a.AttributeClass));
		if (attributeData is null)
			return;

		AddUnsupportedDataAnnotationsDiagnostic(
			diagnostics,
			attributeData,
			string.Format(
				CultureInfo.InvariantCulture,
				"{0} on '{1}' cannot be generated safely for '{2}'.",
				attributeName,
				propertyName,
				propertyType.ToDisplayString()
			)
		);
	}

	static void GenerateCompareValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		INamedTypeSymbol? containingType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		List<DiagnosticInfo> diagnostics
	)
	{
		var compareAttribute = CompareAttributeData.FromAttributeData(attributes);
		if (!compareAttribute.Exists)
			return;

		var otherPropertyName = compareAttribute.OtherProperty;
		var otherProperty = containingType?.GetMembers(otherPropertyName).OfType<IPropertySymbol>().FirstOrDefault();
		if (otherProperty is null)
		{
			diagnostics.Add(
				DiagnosticInfo.Create(
					DiagnosticLibrary.ComparePropertyNotFound,
					property.Locations.FirstOrDefault(),
					propertyName,
					otherPropertyName
				)
			);
			return;
		}

		var displayName = GetDisplayName(property);
		var otherDisplayName =
			compareAttribute.OtherPropertyDisplayName ?? GetDisplayName(otherProperty) ?? otherPropertyName;
		var messageExpression = BuildMessageExpression(
			outputContext,
			diagnostics,
			attributes.FirstOrDefault(static a =>
				TypeLibrary.DataAnnotations.CompareAttribute.Equals(a.AttributeClass)
			),
			displayName,
			compareAttribute.ValidationAttribute,
			CodeGenHelpers.Quote($"Field '{displayName}' must match '{otherDisplayName}'.")
		);

		using (
			outputContext.Writer.OpenBlockScope(
				$"if (!global::System.Collections.Generic.EqualityComparer<object>.Default.Equals(value.{propertyName}, value.{otherPropertyName}))"
			)
		)
		{
			WriteValidationError(
				outputContext,
				"mismatch",
				messageExpression,
				CodeGenHelpers.GetPathFieldName(propertyName)
			);
		}

		outputContext.Writer.WriteLine();
	}

	static bool IsSourceDefinedComplexType(INamedTypeSymbol type) =>
		type.Locations.Any(static l => l.IsInSource) && IsComplexType(type);

	static bool IsComplexType(INamedTypeSymbol type) => !IsScalarType(type) && type.TypeKind is not TypeKind.Enum;

	static ITypeSymbol? GetCollectionElementType(ITypeSymbol propertyType)
	{
		if (propertyType is IArrayTypeSymbol arrayType)
			return arrayType.ElementType;

		if (propertyType is not INamedTypeSymbol namedType)
			return null;

		foreach (var iface in namedType.AllInterfaces)
		{
			if (TypeHelpers.Implements(iface, TypeLibrary.Collections.IEnumerableT))
				return iface.TypeArguments[0];
		}

		if (namedType.IsGenericType && TypeHelpers.Implements(namedType, TypeLibrary.Collections.IEnumerableT))
			return namedType.TypeArguments[0];

		// If the property type implements IEnumerable but not IEnumerable<T>, we cannot determine the element type.
		return null;
	}

	static void GenerateCollectionElementValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol elementType,
		string propertyName
	)
	{
		outputContext.Debug(
			$"Generating collection element validation for property '{property.Name}' of type '{elementType.ToDisplayString()}'",
			1
		);

		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)elementType);
		var collectionValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Collection");
		var itemValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Item");
		var itemResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "ItemResult");
		var indexName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Index");
		var canItemBeNull = TypeHelpers.CanBeNull(elementType);

		outputContext.Writer.WriteLine($"var {collectionValueName} = value.{propertyName};");
		using (outputContext.Writer.OpenBlockScope($"if ({collectionValueName} is not null)"))
		{
			outputContext.Writer.WriteLine($"var {indexName} = 0;");
			using (outputContext.Writer.OpenBlockScope($"foreach (var {itemValueName} in {collectionValueName})"))
			{
				if (canItemBeNull)
				{
					using (outputContext.Writer.OpenBlockScope($"if ({itemValueName} is not null)"))
					{
						outputContext.Writer.WriteLine(
							$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
						);
						using (outputContext.Writer.OpenBlockScope($"if (!{itemResultName}.IsSuccess)"))
						{
							outputContext.Writer.WriteLine(
								$"AddNestedErrors(ref errors, {itemResultName}, {CodeGenHelpers.Quote(propertyName)}, {indexName});"
							);
						}
					}
				}
				else
				{
					outputContext.Writer.WriteLine(
						$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
					);
					using (outputContext.Writer.OpenBlockScope($"if (!{itemResultName}.IsSuccess)"))
					{
						outputContext.Writer.WriteLine(
							$"AddNestedErrors(ref errors, {itemResultName}, {CodeGenHelpers.Quote(propertyName)}, {indexName});"
						);
					}
				}

				outputContext.Writer.WriteLine($"{indexName}++;");
			}
		}

		outputContext.Writer.WriteLine();
	}

	static void GenerateComplexTypeValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		string propertyName,
		bool canBeNull
	)
	{
		outputContext.Debug(
			$"Generating complex type validation for property '{property.Name}' of type '{propertyType.ToDisplayString()}'",
			1
		);
		var propertyValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Value");
		var nestedResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Result");
		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)propertyType);

		outputContext.Writer.WriteLine($"var {propertyValueName} = value.{propertyName};");
		if (canBeNull)
		{
			using (outputContext.Writer.OpenBlockScope($"if ({propertyValueName} is not null)"))
			{
				outputContext.Writer.WriteLine(
					$"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});"
				);
				using (outputContext.Writer.OpenBlockScope($"if (!{nestedResultName}.IsSuccess)"))
				{
					outputContext.Writer.WriteLine(
						$"AddNestedErrors(ref errors, {nestedResultName}, {CodeGenHelpers.Quote(propertyName)});"
					);
				}
			}
		}
		else
		{
			outputContext.Writer.WriteLine($"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});");
			using (outputContext.Writer.OpenBlockScope($"if (!{nestedResultName}.IsSuccess)"))
			{
				outputContext.Writer.WriteLine(
					$"AddNestedErrors(ref errors, {nestedResultName}, {CodeGenHelpers.Quote(propertyName)});"
				);
			}
		}
	}

	static void GeneratePathFields(SchemaGenerationOutputContext outputContext, CancellationToken cancellationToken)
	{
		foreach (var property in outputContext.ZodSchema.Properties)
		{
			cancellationToken.ThrowIfCancellationRequested();
			outputContext.Writer.WriteField(
				new(
					CodeGenHelpers.GetPathFieldName(property.Value.Name),
					TypeLibrary.Collections.ImmutableArray.MakeGeneric(PurviewTypeLibrary.System.String),
					TypeDeclarationAccessibility.Private
				)
				{
					IsStatic = true,
					IsReadOnly = true,
					Initializer = TypeLibrary.Collections.ImmutableArray.StaticMember(
						$"Create({CodeGenHelpers.Quote(property.Value.Name)})"
					),
				}
			);
		}
	}

	static void GenerateStaticAttributeFields(
		SchemaGenerationOutputContext outputContext,
		CancellationToken cancellationToken
	)
	{
		foreach (var property in outputContext.ZodSchema.Properties)
		{
			cancellationToken.ThrowIfCancellationRequested();

			if (property.Value.ValidationAttributes.RegularExpression.ShouldProcess)
			{
				outputContext.Writer.WriteLine(
					$"static readonly global::System.Text.RegularExpressions.Regex {GetRegexFieldName(property.Value.Name)} = new({CodeGenHelpers.Quote(property.Value.ValidationAttributes.RegularExpression.Value.Pattern!)}, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);"
				);
			}

			if (property.Value.ValidationAttributes.Range.ShouldProcess)
			{
				outputContext.Writer.WriteLine(
					$"static readonly {property.Value.PropertyType} {GetRangeMinimumFieldName(property.Value.Name)} = {property.Value.ValidationAttributes.Range.Value.MinimumExpression};"
				);
				outputContext.Writer.WriteLine(
					$"static readonly {property.Value.PropertyType} {GetRangeMaximumFieldName(property.Value.Name)} = {property.Value.ValidationAttributes.Range.Value.MaximumExpression};"
				);
			}
		}

		outputContext.Writer.WriteLine();
	}

	static void GenerateValidationHelpers(
		SchemaGenerationOutputContext outputContext,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var writer = outputContext.Writer;
		writer.WriteLine(
			$"static void AddError(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError).AsTypeReference().Nullable()} errors, {TypeLibrary.ValidationError} error)"
		);
		using (writer.OpenBlockScope())
		{
			writer.WriteLine(
				$"(errors ??= new {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}()).Add(error);"
			);
		}

		using (
			writer.OpenBlockScope(
				$"static void AddNestedErrors<T>(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError).AsTypeReference().Nullable()} errors, {TypeLibrary.ValidationResult}<T> nestedResult, string prefix)"
			)
		)
		{
			using (writer.OpenBlockScope("foreach (var error in nestedResult.Errors)"))
			{
				writer.WriteDelimitedBlock(
					"AddError",
					"(",
					");",
					errorArguments =>
						errorArguments.WriteDelimitedBlock(
							$"ref errors, {TypeLibrary.ValidationError}.Create",
							"(",
							")",
							createArguments =>
							{
								createArguments.WriteLine("error.Code,");
								createArguments.WriteLine("error.Message,");
								createArguments.WriteLine(
									$"{TypeLibrary.Collections.ImmutableArray}.Create(prefix).AddRange(error.Path),"
								);
								createArguments.WriteLine("error.Parameters,");
								createArguments.WriteLine("error.Origin,");
								createArguments.WriteLine("error.Minimum,");
								createArguments.WriteLine("error.Maximum,");
								createArguments.WriteLine("error.Inclusive");
							}
						)
				);
			}
		}

		writer.WriteLine();
		using (
			writer.OpenBlockScope(
				$"static void AddNestedErrors<T>(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}? errors, {TypeLibrary.ValidationResult}<T> nestedResult, string prefix, int index)"
			)
		)
		{
			using (writer.OpenBlockScope("foreach (var error in nestedResult.Errors)"))
			{
				writer.WriteLine($"AddError(ref errors, {TypeLibrary.ValidationError}.Create(");
				writer.Indent();
				writer.WriteLine("error.Code,");
				writer.WriteLine("error.Message,");
				writer.WriteLine(
					$"{TypeLibrary.Collections.ImmutableArray}.Create(prefix, index.ToString()).AddRange(error.Path),"
				);
				writer.WriteLine("error.Parameters,");
				writer.WriteLine("error.Origin,");
				writer.WriteLine("error.Minimum,");
				writer.WriteLine("error.Maximum,");
				writer.WriteLine("error.Inclusive");
				writer.Unindent();
				writer.WriteLine("));");
			}
		}

		writer.WriteLine();
		writer.WriteLine("static string FormatCount(int count, string singularNoun, string pluralNoun)");
		using (writer.OpenBlockScope())
		{
			writer.WriteLine("return count == 1 ? $\"1 {singularNoun}\" : $\"{count} {pluralNoun}\";");
		}

		writer.WriteLine();
	}

	static void GenerateParseMethod(SchemaGenerationOutputContext outputContext, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();

		outputContext
			.Writer.XmlSummary("Validates and returns the value, throwing an exception if validation fails.")
			.XmlParam("value", "The value to validate and return.")
			.XmlReturn("The validated value.");
		using (
			outputContext.Writer.OpenBlockScope(
				$"public static {outputContext.ZodSchema.TargetType} Parse({outputContext.ZodSchema.TargetType} value)"
			)
		)
		{
			outputContext.Writer.WriteLine("return Validate(value).GetValueOrThrow();");
		}
	}

	static void GenerateCompositionMethods(
		SchemaGenerationOutputContext outputContext,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();
		outputContext.Debug($"Generating value-first composition methods for {outputContext.ZodSchema.TargetType}", 1);

		var validationResultType = TypeLibrary.ValidationResult.MakeGeneric(outputContext.ZodSchema.TargetType);

		void WriteFailure(CodeWriter body, string fallbackMessage) =>
			body.WriteDelimitedBlock(
				$"return {validationResultType}.Failure",
				"(",
				");",
				failureArguments =>
					failureArguments.WriteDelimitedBlock(
						$"{TypeLibrary.ValidationError}.Create",
						"(",
						")",
						errorArguments =>
						{
							errorArguments.Quote("validation_failed").WriteLine(",");
							errorArguments.WriteLine($"message ?? \"{fallbackMessage}\",");
							errorArguments.WriteLine("EmptyPath");
						}
					)
			);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and then requires an additional predicate to pass (value-first .and()).",
			"Equivalent to Zod's .and() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyAnd("
				+ $"{outputContext.ZodSchema.TargetType} value, "
				+ $"global::System.Func<{outputContext.ZodSchema.TargetType}, bool> additionalValidation, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (!result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (!additionalValidation(value))",
					ifBody => WriteFailure(ifBody, $"Additional validation failed for {classSymbol.Name}")
				);

				method.NewLine();
				method.WriteLine("return result;");
			}
		);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and accepts it if either the schema or an alternative predicate passes (value-first .or()).",
			"Equivalent to Zod's .or() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyOr("
				+ $"{outputContext.ZodSchema.TargetType} value, "
				+ $"global::System.Func<{outputContext.ZodSchema.TargetType}, bool> alternativeValidation, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (alternativeValidation(value))",
					ifBody => ifBody.WriteLine($"return {validationResultType}.Success(value);")
				);

				method.NewLine();

				WriteFailure(method, $"Neither validation passed for {outputContext.ZodSchema.TargetType.Name}");
			}
		);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and then runs a custom refinement predicate (value-first .refine()).",
			"Equivalent to Zod's .refine() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyRefine("
				+ $"{outputContext.ZodSchema.TargetType} value, "
				+ $"global::System.Func<{outputContext.ZodSchema.TargetType}, bool> refinement, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (!result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (!refinement(value))",
					ifBody =>
						WriteFailure(
							ifBody,
							$"Refinement validation failed for {outputContext.ZodSchema.TargetType.Name}"
						)
				);

				method.NewLine();
				method.WriteLine("return result;");
			}
		);

		outputContext.Writer.NewLine();
	}
}
